databases:
  - name: mpesaprompt_db
    databaseName: mpesaprompt_db
    user: mpesaprompt_user

services:
  - type: web
    name: backend
    runtime: python
    region: ohio
    plan: free
    cwd: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask db upgrade && flask init-db && gunicorn backend.manage:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mpesaprompt_db
          property: connectionString
      - key: FLASK_APP
        value: backend.manage
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false


  - type: static
    name: frontend
    region: ohio
    plan: free
    cwd: ./frontend/client
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
